SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE `order` ADD COLUMN `last4`  int(4) UNSIGNED NOT NULL AFTER `total`;
ALTER TABLE `order` MODIFY COLUMN `warehouseId`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `addressId`;
ALTER TABLE `order_items` DROP FOREIGN KEY `order_items_fk_2`;
ALTER TABLE `order_items` DROP FOREIGN KEY `order_items_fk_1`;
ALTER TABLE `order_items` ADD COLUMN `orderId`  int(11) UNSIGNED NOT NULL AFTER `accountId`;
ALTER TABLE `order_items` DROP PRIMARY KEY;
ALTER TABLE `order_items` ADD PRIMARY KEY (`accountId`, `orderId`);
ALTER TABLE `order_items` ADD CONSTRAINT `order_items_fk_3` FOREIGN KEY (`orderId`) REFERENCES `order` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `order_items` ADD CONSTRAINT `order_items_fk_1` FOREIGN KEY (`accountId`) REFERENCES `account` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `order_items` ADD CONSTRAINT `order_items_fk_2` FOREIGN KEY (`itemId`) REFERENCES `inventory` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
CREATE INDEX `order_items_fk_3` ON `order_items`(`orderId`) USING BTREE ;
SET FOREIGN_KEY_CHECKS=1;